services:
  database:
    container_name: pharos-database
    restart: always
    image: mysql:8.0
    ports:
      - '3307:3306'
    env_file:
      - .env
    volumes:
      - /volumes/mysql_data:/var/lib/mysql
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost']
      interval: 10s
      timeout: 5s
      retries: 5

    networks:
      - pharos-network

  api:
    container_name: pharos-api
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '5000:5000'
    env_file:
      - .env
    networks:
      - pharos-network
    depends_on:
      database:
        condition: service_healthy

  pipeline:
    container_name: pharos-pipeline
    restart: always
    build:
      context: ../Pharos-Pipeline
      dockerfile: Dockerfile
    env_file:
      - .env
    networks:
      - pharos-network
    ports:
      - '5001:5001'

volumes:
  mysql_data:

networks:
  pharos-network:
    name: pharos-network
    driver: bridge
